name: Hi Intel
on: push
env:
  username: Mona
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo 'Hi ${{ env.username }}'  # Hi Mona
      - run: echo 'Hi ${{ env.username }}'  # Hi Mona
        env:
          username: KS
  linux_job:
    runs-on: ubuntu-latest
    env:
      username: KS1
    steps:
      - run: echo 'Hi ${{ env.username }}'  # Hi Tux
